catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]
urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]
urlpatterns += [
    path('borrowed/', views.LoanedBooksListView.as_view(), name='all-borrowed'),
]
urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]
urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]
urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]
urlpatterns += [
    path('book',views.BookGenreListView.as_view(),name='books-genre'),
]
urlpatterns += [
    path('book/booksbygenre',views.get_genre,name='books-by-genre'),
]
#urlpatterns += [
#    path('book/listbooksbygenre/<str:genre>',views.BookByGenreListView.as_view(),name='list-books-by-genre'),
#]
urlpatterns += [
    path('book/listbooksbygenre<str:genre>',views.show_books_by_genre,name='list-books-by-genre'),
]
urlpatterns += [
    path('book/books',views.get_book_borrow_id,name='borrow-renew'),
]
urlpatterns += [
    path('book/bookborrow',views.set_book_borrow,name='my-borrow'),
]
urlpatterns += [
    path('book/exportbooks',views.do_export_books,name='export-books'),
]
urlpatterns += [
    path('book/importbooks',views.import_books,name='import-books'),
]
urlpatterns += [
    path('book/searchbooks',views.search_books,name='search-books'),
]
urlpatterns += [
    path('book/<str:choice>/<str:title_search>/<str:thegenre>/<str:author>/searchresults',views.search_results,name='search-results'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
# Create your models here.
class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name
    class Meta:
        ordering = ['name']
        
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                             help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    author = models.ManyToManyField(Author, help_text='Select a author for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'
    def display_authors(self):
        """Create a string for the Author. This is required to display author in Admin."""
        return ', '.join(author.first_name+' '+author.last_name for author in self.author.all()[:3])
    def list_authors(self):
        """Create a string for the Author. This is required to display author in Admin."""
        return ';'.join(author.first_name+','+author.last_name for author in self.author.all()[:3])


    display_authors.short_description = 'Authors'
    class Meta:
        ordering = ['title']
import uuid # Required for unique book instances
from django.contrib.auth.decorators import permission_required


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)
    def __str__(self):
        """String for representing the Model object."""
        mystatus = ""
        for a_status in self.LOAN_STATUS:
            if a_status[0] == self.status:
                mystatus = a_status[1]
                break
        if self.due_back != None:
            dueback = self.due_back.isoformat()
        else:
            dueback = "TBD"
        return f'{self.id} ({self.book.title,mystatus,dueback})'
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
    

catalog/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from .models import Genre,Book,BookInstance,Author

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data
class GenreForm(forms.Form):
    
    genres = Genre.objects.all()
    CHOICES =[]
    for a_genre in genres:
        CHOICES.append((a_genre,a_genre))
    choice = forms.ChoiceField(choices=CHOICES)
class BookSearchForm(forms.Form):
    
    CHOICES =[('Genre','Genre'),('Title','Title'),('Author','Author')]
    choice = forms.ChoiceField(choices=CHOICES)
    title_search = forms.CharField(required=False,initial=" ")
    
    genres = Genre.objects.all()
    CHOICES1 =[]
    for a_genre in genres:
        CHOICES1.append((a_genre.name,a_genre.name))
    genre = forms.ChoiceField(choices=CHOICES1)
    authors = Author.objects.all()
    CHOICES2 =[]
    for a_author in authors:
        CHOICES2.append((a_author,a_author))
    author = forms.ChoiceField(choices=CHOICES2)
class BookForm(forms.Form):
    
    books = Book.objects.all()
    CHOICES =[]
    for a_book in books:
        CHOICES.append((a_book.title,a_book.title))
    choice = forms.ChoiceField(choices=CHOICES)
class BookInstanceForm(forms.Form):
    bookinstances = BookInstance.objects.all()
    CHOICES =[]
    for a_bookinstance in bookinstances:
        CHOICES.append((a_bookinstance.book.title,a_bookinstance.book.title))
    choice = forms.ChoiceField(choices=CHOICES)
    

catalog/templates/catalog/.#book_detail.html
richard@Fedora34-lt.richard.org.3096:1633298055

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Request To Borrow {{ title }}</h1>
<p>Email sent</p>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>
<p><strong>Author(s):</strong>
  {% for author in book.author.all %}
  <a href="{{ author.get_absolute_url }}">{{ author }}</a>
{% endfor%}</p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_exported.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Request To Borrow {{ title }}</h1>
<p>Email sent</p>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({% if bookinst.due_back %}{{ bookinst.due_back }}{% else %} No due date {% endif %})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/books_exported.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Exported {{ count }} Books</h1>
<p> Email sent </p>
{% endblock %}

catalog/templates/catalog/books_imported.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Imported {{ count }} Books</h1>
{% endblock %}

catalog/templates/catalog/found_books.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Found {{ size }} Books</h1>
  {% if choice  == 'Title' %}
  <h2> That contain '{{ title_search }}' </h2>
    {% endif %}
  {% if choice  == 'Genre' %}
  <h2> For Genre '{{ thegenre }}' </h2>
    {% endif %}
  {% if choice  == 'Author' %}
  <h2> For Author '{{ theauthor }}' </h2>
    {% endif %}
  <div class="books-by-genre">
  {% if page_obj %}
  <ul>
    {% for book in page_obj %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author.all|join:";" }} )
      </li>
    {% endfor %}
  </ul>
  
  {% else %}
    <p>There are no books in the library.</p>
    {% endif %}
    </div>
<div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
            <!-- <a href="?page=1">&laquo; first</a> -->
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <!--<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> -->
        {% endif %}
    </span>
</div>{% endblock %}

catalog/templates/catalog/genre_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Genre List</h1>
  {% if genre_list %}
  <ul>
    {% for genre in genre_list %}
      <li>
        {{genre}}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no genres in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/list_books_by_genre.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List by Genre</h1>
  <h2> Genre is {{ genre }} </h2>
  <div class="books-by-genre">
  {% if page_obj %}
  <ul>
    {% for book in page_obj %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author.all|join:";" }} )
      </li>
    {% endfor %}
  </ul>
  
  {% else %}
    <p>There are no books in the library.</p>
    {% endif %}
    </div>
<div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
            <!-- <a href="?page=1">&laquo; first</a> -->
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <!--<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> -->
        {% endif %}
    </span>
</div>{% endblock %}